{
 "title": "Valday Weather",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Temp current",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "weather_temperature_kelvin{type=\"current\"}-273.15"
    }
   ]
  },
  {
   "title": "Temperature Celsius",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "weather_temperature_kelvin{type=\"current\"}-273.15",
     "legendFormat": "Temp(C)"
    }
   ]
  },
  {
   "title": "Pressure mmHg",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "weather_pressure_hectopascal{level=\"ground\"}/1.33322"
    }
   ]
  },
  {
   "title": "Pressure mmHg",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    {
     "expr": "weather_pressure_hectopascal{level=\"ground\"}/1.33322"
    }
   ]
  },
  {
   "title": "Wind direction",
   "type": "briangann-gauge-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "format": "degree",
   "targets": [
    { "expr": "weather_wind_direction" }
   ]
  },
  {
   "title": "Wind speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "weather_wind_meters_per_second" }
   ]
  }
 ]
}